[package]
name = "ecdsa"
version = "0.1.0"
authors = ["rishflab <rishflab@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
secp256kfun = "0.6"
sha2 = "0.9"
rand = "0.8"